#!/bin/bash

/bin/mount /dev/sda /mnt/

if ! /bin/restic -r /mnt/home-backup \
  --password-file /home/sultan/Documents/notes/private/keys/restic-password \
  cat config >/dev/null 2>&1
then
  /bin/restic -r /mnt/home-backup \
    --password-file /home/sultan/Documents/notes/private/keys/restic-password \
    init
fi

/bin/restic -r /mnt/home-backup --password-file /home/sultan/Documents/notes/private/keys/restic-password backup / \
  --exclude-caches \
  --exclude-file /home/sultan/Documents/scripts/exclude.txt

/bin/restic -r /mnt/home-backup \
  --password-file /home/sultan/Documents/notes/private/keys/restic-password \
  forget --keep-last 5 --prune

/bin/sync
/bin/umount /dev/sda
