#!/bin/bash

/bin/mount /dev/sda /mnt/
/bin/restic -r /mnt/home-backup --password-file /home/sultan/notes/private/restic-password backup / \
  --exclude-caches \
  --exclude-file /home/sultan/Documents/scripts/exclude.txt
/bin/restic forget --keep-last 5
/bin/sync
/bin/umount /dev/sda
